---
swagger: "2.0"
info:
  description: "Ertnode API"
  version: "1"
  title: "ErtCDN"
basePath: "/api/cdn/v1/"
schemes:
- "http"
paths:
  /resource:
    get:
      tags:
      - "CDN"
      summary: "get cdn resource"
      description: "Post and retrieve self or foreign Portfolio"
      operationId: "getResource"
      produces:
      - "*/*"
      parameters:
      - name: "hkey"
        in: "query"
        description: "retrieve resource by hkey"
        required: true
        type: "string"
        maxLength: 64
        minLength: 64
      responses:
        200:
          description: "ok"
        400:
          description: "err"
    post:
      tags:
      - "CDN"
      summary: Uploads a file.
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: ufile
          type: file
          description: The file to upload.
      responses:
        201:
          description: "object created"
          schema:
            type: "string"
            maxLength: 64
            minLength: 64
  /reqheaders:
    get:
      tags:
      - "CDN"
      summary: "get client request headers"
      description: "retrieve request headers map"
      operationId: "getReqHeaders"
      produces:
      - "*/*"
      responses:
        200:
          description: "ok"
        400:
          description: "err"
  /info:
    get:
      tags:
      - "CDN"
      summary: "get CDN info"
      description: "retrieve cdn geo and info"
      operationId: "getReqHeaders"
      produces:
      - "*/*"
      responses:
        200:
          description: "ok"
        400:
          description: "err"
  /idx:
    get:
      tags:
      - "CDN"
      summary: "search gigs"
      description: "search gigs filtered by prefixes, category, tags, range"
      operationId: "getReqHeaders"
      produces:
      - "*/*"
      parameters:
      - name: "text"
        in: "query"
        required: false
      - name: "tags"
        in: "query"
        required: false
      - name: "category"
        in: "query"
        required: false
      - name: "q1range"
        in: "query"
        required: false
      - name: "limit"
        in: "query"
        required: false
        default: 1000

      responses:
        200:
          description: "retrieve ordered gig hash list"
        400:
          description: "err"

  /track:
    put:
      tags:
      - "Track CDNs in cluster"
      summary: "Track cluster"
      description: "Track cluster"
      operationId: "joinCDnCluster"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "data"
        description: "cdn join"
        required: false
        schema:
          type: string
      responses:
        203:
          description: "Updated"
        400:
          description: "something wrong"
    get:
      tags:
      - "Track CDNs in cluster"
      summary: "getTrackData"
      description: "getTrackData"
      operationId: "getTrackData"
      produces:
      - "*/*"

